AWSTemplateFormatVersion: 2010-09-09
Description: Relicblade Decks Backend
Transform: AWS::Serverless-2016-10-31
Parameters:
  AppId:
    Type: String

Resources:
  DecksAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: DecksAPIGateway
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /sharedDeck:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DecksAPILambda.Arn}/invocations
              responses: {}
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DecksAPILambda.Arn}/invocations
              responses: {}
          /sharedCards:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DecksAPILambda.Arn}/invocations
              responses: {}
          /storeDeck:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DecksAPILambda.Arn}/invocations
              responses: {}
          /uploadCards:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DecksAPILambda.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: 5
  DecksAPILambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles the decks
      CodeUri: ./server
      Handler: app.handler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 60
      Tracing: Active
      Events:
        DecksAPIGatewayGETsharedDeck:
          Type: Api
          Properties:
            Path: /sharedDeck
            Method: GET
            RestApiId: !Ref DecksAPIGateway
        DecksAPIGatewayPOSTsharedDeck:
          Type: Api
          Properties:
            Path: /sharedDeck
            Method: POST
            RestApiId: !Ref DecksAPIGateway
        DecksAPIGatewayGETsharedCards:
          Type: Api
          Properties:
            Path: /sharedCards
            Method: GET
            RestApiId: !Ref DecksAPIGateway
        DecksAPIGatewayPOSTstoreDeck:
          Type: Api
          Properties:
            Path: /storeDeck
            Method: POST
            RestApiId: !Ref DecksAPIGateway
        DecksAPIGatewayPOSTuploadCards:
          Type: Api
          Properties:
            Path: /uploadCards
            Method: POST
            RestApiId: !Ref DecksAPIGateway
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
  DecksAPILambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${DecksAPILambda}
  DecksSharedDeck:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: "DecksSharedDecks"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  DecksSavedDeck:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: "DecksSavedDecks"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  DecksCards:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: "DecksCards"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
